### ISSUE TITLE
Calculator Crash without bc which is used for command line calculator on Linux

### ISSUE THREAD

**Issue by longlongvip** [HVML/xGUI-Pro#7]
## Aren't you using Linux, why is there no bc command?
I use Arch Linux, and I don't install bc, you can install bc by typing `sudo pacman -s bc` on Arch Linux
## Calculator should not crash
Calculator should not crash even without bc and some tips should be given
## Calculator works
Calculator works after I installed bc
```bash
sudo pacman -s bc
```

**Comment by VincentWei** [comment]
Thanks for your report!

However, this bug should belong to PurC, not xGUI Pro. :)

**Comment by longlongvip** [comment]
I will report it in [PurC](https://github.com/HVML/PurC)
